# Generated by Django 4.0.4 on 2023-01-13 07:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('main', '0002_requestersrequest_user_riderrequest_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestersrequest',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requestersrequest', to=settings.AUTH_USER_MODEL),
        ),
    ]
