# Generated by Django 4.0.4 on 2023-01-13 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_requestersrequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestersrequest',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
